### ISSUE TITLE
Add support for bulk creation of objects with multi-value attributes

### ISSUE THREAD

**Issue by jathanism** [dropbox/pynsot#123]
It appears that we may have completely overlooked the ability to create objects in bulk that have multi-value attributes (e.g. where the attribute on the server side has `multi=True`).

We'll need to come up with a way to represent these. It might be better to reconsider the entire format of the bulk file to something more descriptive than the "colon-separated" format we have now.

**Comment by jathanism** [comment]
Maybe change this thing to YAML? For example:

```yaml
- hostname: foo-bar1
  attributes:
    foo: bar
    access_methods: [m1, m2, m3]
- hostname: foo-bar2
  attributes:
    foo: baz
    access_methods: [m4, m5, m6]
```

Which parses into:

```python
[
    {
        "attributes": {
            "access_methods": [
                "m1",
                "m2",
                "m3"
            ],
            "foo": "bar"
        },
        "hostname": "foo-bar1"
    },
    {
        "attributes": {
            "access_methods": [
                "m4",
                "m5",
                "m6"
            ],
            "foo": "baz"
        },
        "hostname": "foo-bar2"
    }
]
```
